basePath: /
definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
  handler.signInInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  types.BannerRequest:
    properties:
      banner_id:
        type: integer
      content:
        $ref: '#/definitions/types.Content'
      feature_id:
        type: integer
      is_active:
        type: boolean
      tag_ids:
        items:
          type: integer
        type: array
    type: object
  types.BannerResponse:
    properties:
      banner_id:
        type: integer
      content:
        $ref: '#/definitions/types.Content'
      feature_id:
        type: integer
      is_active:
        type: boolean
      tag_ids:
        items:
          type: integer
        type: array
    type: object
  types.Content:
    properties:
      text:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  types.User:
    properties:
      is_admin:
        type: boolean
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Server for BannersShow Application for avito backend trainee
  title: Banners Show App API
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя
      operationId: login-user
      parameters:
      - description: Учетные данные
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: Токен
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Вход
      tags:
      - auth
  /auth/sign-in/admin:
    post:
      consumes:
      - application/json
      description: Авторизация администратора
      operationId: login-admin
      parameters:
      - description: Учетные данные
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: Токен
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Вход администратора
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Создание учетной записи пользователя
      operationId: create-user-account
      parameters:
      - description: Информация об аккаунте
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/types.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Регистрация
      tags:
      - auth
  /auth/sign-up/admin:
    post:
      consumes:
      - application/json
      description: Создание учетной записи администратора
      operationId: create-admin-account
      parameters:
      - description: Информация об аккаунте
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/types.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Регистрация администратора
      tags:
      - auth
  /banner:
    get:
      consumes:
      - application/json
      description: Получение списка баннеров
      operationId: get-banners
      parameters:
      - in: query
        name: feature_id
        type: integer
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      - in: query
        name: tag_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Список баннеров
          schema:
            items:
              $ref: '#/definitions/types.BannerResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get Banners
      tags:
      - Banners
    post:
      consumes:
      - application/json
      description: create Banner
      operationId: create-banner
      parameters:
      - description: banner info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/types.BannerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create Banner
      tags:
      - Banners
  /banner/{id}:
    delete:
      description: Удаление баннера
      operationId: delete-banner
      parameters:
      - description: Идентификатор баннера
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Баннер успешно удален
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete Banner
      tags:
      - Banners
    patch:
      consumes:
      - application/json
      description: Обновление информации о баннере
      operationId: update-banner
      parameters:
      - description: Идентификатор баннера
        in: path
        name: id
        required: true
        type: integer
      - description: Информация о баннере
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/types.BannerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update Banner
      tags:
      - Banners
  /user_banner:
    get:
      consumes:
      - application/json
      description: Получение баннера пользователя
      operationId: get-user-banner
      parameters:
      - in: query
        name: feature_id
        type: integer
      - in: query
        name: tag_id
        type: integer
      - in: query
        name: use_last_revision
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: Баннер пользователя
          schema:
            $ref: '#/definitions/types.Content'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get User Banner
      tags:
      - Banners
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
